"""Initial migration. Create table 'city_distances'

Revision ID: 87e5b58c500d
Revises: 
Create Date: 2023-03-19 10:36:00.051107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87e5b58c500d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_distances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city_from", sa.Integer(), nullable=False),
        sa.Column("city_to", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city_distances")
    # ### end Alembic commands ###
